services:
  db:
    container_name: stage_mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
  web:
    container_name: stage_backend
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # Ensure this maps the collected static files
      - media_volume:/app/media  # Media files mapping if needed
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    container_name: stage_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf  # Mounting the development Nginx config
      - static_volume:/vol/staticfiles
      - media_volume:/vol/media
    # environment:
    #   - DEBUG=True  # Set environment variables for development (not working)

volumes:
  mysql_data:
  static_volume:
  media_volume: