# Generated by Django 5.0.3 on 2024-03-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='pass_mark',
            field=models.PositiveIntegerField(default=80, help_text='Percentage Pass Mark'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
