# Generated by Django 5.0.3 on 2024-03-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_subject_remove_customuser_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='School'),
        ),
    ]
