# Generated by Django 5.0.3 on 2024-03-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizattempt_percentage_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
