# Generated by Django 5.0.3 on 2024-03-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizattempt_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_options',
            field=models.ManyToManyField(to='quiz.option'),
        ),
    ]
