# Generated by Django 5.0.3 on 2024-03-15 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_option_question_alter_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='quiz.subject'),
        ),
    ]
