name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Tag
        id: set-tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAG=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/kubs" ]]; then
            echo "TAG=kubs" >> $GITHUB_ENV
          else
            echo "TAG=staging" >> $GITHUB_ENV
          fi

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Show Working Directory Contents
        run: ls -R

      - name: Build & Push Backend Image
        run: |
          docker build \
            --build-arg DJANGO_ENV=${{ env.TAG }} \
            -t ${{ secrets.DOCKER_USERNAME }}/quizcloud:${{ env.TAG }} \
            -f Dockerfile.${{ env.TAG }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/quizcloud:${{ env.TAG }}