name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy to server using SSH
      - name: Deploy, Migrate, and Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/saka/quiz-cloud

            # Pull the latest changes
            git pull origin main

            # Stop the running containers
            docker-compose down

            # Build and start the Docker containers with --build
            docker-compose up --build -d

            # Run Django migrations
            docker-compose exec web python manage.py migrate

            # Collect static files
            docker-compose exec web python manage.py collectstatic --noinput

            # Check if Certbot is installed on the server
            if ! command -v certbot &> /dev/null; then
              sudo apt-get update
              sudo apt-get install certbot python3-certbot-nginx -y
            else
              echo "Certbot already installed"
            fi

            # Obtain SSL certificates if not already obtained
            if [ ! -d "/etc/letsencrypt/live/pointsystem.tech" ]; then
              docker-compose run --rm certbot certonly --webroot --webroot-path=/var/www/certbot -d pointsystem.tech -d www.pointsystem.tech
            else
              echo "SSL certificate already exists"
            fi

            # Restart Nginx to apply SSL
            # docker-compose restart nginx

            # Restart the containers if needed
            docker-compose restart